# Site settings
title: My 2021 Christmas with friends
description: “Life is not measured by the number of breaths we take, but by the moments that take our breath away.”- Hillary Cooper
baseurl: "/Christmas-with-friends-2021" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
