# Site settings
title: My 2021 Christmas with friends
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "/Christmas-with-friends-2021" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
